import { createHash, randomBytes } from "node:crypto";
import { mkdir, readFile, rename, rm, writeFile } from "node:fs/promises";
import path from "node:path";

/**
 * The tool tree: the tools an agent sees, rendered as TypeScript it can list,
 * read and import from code (https://www.anthropic.com/engineering/code-execution-with-mcp).
 * One directory per server, one file per tool, each a typed function that
 * calls the tool through Paseo with the run's own credentials.
 */

export type JsonSchema = Record<string, unknown>;

export interface ToolTreeTool {
  name: string;
  description?: string;
  inputSchema?: JsonSchema;
  outputSchema?: JsonSchema;
}

export interface ToolTreeServer {
  /** `paseo` for the daemon's own tools; otherwise an MCP gateway backend name. */
  name: string;
  tools: ToolTreeTool[];
}

export const PASEO_TOOL_TREE_SERVER = "paseo";

const DIGEST_FILE = ".paseo-tool-tree-digest";
const MAX_SCHEMA_DEPTH = 8;
const IDENTIFIER = /^[A-Za-z_$][A-Za-z0-9_$]*$/;
const RESERVED_WORDS = new Set(
  (
    "break case catch class const continue debugger default delete do else enum export extends " +
    "false finally for function if import in instanceof new null return super switch this throw " +
    "true try typeof var void while with yield let static implements interface package private " +
    "protected public await arguments eval"
  ).split(" "),
);

const CLIENT_SOURCE = `// Generated by Paseo. Calls a tool through Paseo as the agent whose run this is:
// exec and process_spawn give each run PASEO_AGENT_TOKEN, PASEO_MCP_URL and
// PASEO_MCP_GATEWAY_URL. Nothing here holds a credential.

export type ToolContent = Array<{ type: string; text?: string; [key: string]: unknown }>;

interface RunEnv {
  token: string;
  mcpUrl: string;
  gatewayUrl: string | undefined;
}

interface ToolCallResult {
  content?: ToolContent;
  structuredContent?: unknown;
  isError?: boolean;
}

interface JsonRpcResponse {
  id?: number | string | null;
  result?: unknown;
  error?: { code?: number; message?: string };
}

interface Session {
  id: string | null;
  protocolVersion: string;
}

const PROTOCOL_VERSION = "2025-06-18";
const sessions = new Map<string, Promise<Session>>();
let nextId = 1;

function runEnv(): RunEnv {
  const env =
    (globalThis as { process?: { env?: Record<string, string | undefined> } }).process?.env ?? {};
  const token = env.PASEO_AGENT_TOKEN;
  const mcpUrl = env.PASEO_MCP_URL;
  if (!token || !mcpUrl) {
    throw new Error(
      "PASEO_AGENT_TOKEN and PASEO_MCP_URL are not set: run this code with Paseo's exec tool.",
    );
  }
  return { token, mcpUrl, gatewayUrl: env.PASEO_MCP_GATEWAY_URL };
}

function endpoint(server: string, env: RunEnv): string {
  if (server === "paseo") return env.mcpUrl;
  if (!env.gatewayUrl) throw new Error("PASEO_MCP_GATEWAY_URL is not set");
  return \`\${env.gatewayUrl.replace(/\\/+$/, "")}/\${encodeURIComponent(server)}\`;
}

function parseBody(text: string, contentType: string): JsonRpcResponse[] {
  if (!text.trim()) return [];
  if (!contentType.includes("text/event-stream")) {
    const parsed = JSON.parse(text) as JsonRpcResponse | JsonRpcResponse[];
    return Array.isArray(parsed) ? parsed : [parsed];
  }
  const messages: JsonRpcResponse[] = [];
  for (const event of text.split(/\\r?\\n\\r?\\n/)) {
    const data = event
      .split(/\\r?\\n/)
      .filter((line) => line.startsWith("data:"))
      .map((line) => line.slice(5).trimStart())
      .join("\\n");
    if (data) messages.push(JSON.parse(data) as JsonRpcResponse);
  }
  return messages;
}

async function post(
  url: string,
  env: RunEnv,
  session: Session | null,
  message: Record<string, unknown>,
): Promise<{ headers: Headers; response: JsonRpcResponse | null }> {
  const headers: Record<string, string> = {
    "content-type": "application/json",
    accept: "application/json, text/event-stream",
    authorization: \`Bearer \${env.token}\`,
  };
  if (session?.id) headers["mcp-session-id"] = session.id;
  if (session) headers["mcp-protocol-version"] = session.protocolVersion;
  const res = await fetch(url, { method: "POST", headers, body: JSON.stringify(message) });
  const text = await res.text();
  if (!res.ok) {
    throw new Error(\`\${url} answered \${res.status}: \${text.slice(0, 500)}\`);
  }
  const id = message.id;
  const response =
    id === undefined
      ? null
      : (parseBody(text, res.headers.get("content-type") ?? "").find((m) => m.id === id) ?? null);
  return { headers: res.headers, response };
}

function openSession(url: string, env: RunEnv): Promise<Session> {
  let session = sessions.get(url);
  if (!session) {
    session = (async () => {
      const { headers, response } = await post(url, env, null, {
        jsonrpc: "2.0",
        id: nextId++,
        method: "initialize",
        params: {
          protocolVersion: PROTOCOL_VERSION,
          capabilities: {},
          clientInfo: { name: "paseo-tool-tree", version: "1" },
        },
      });
      if (!response || response.error) {
        throw new Error(\`MCP initialize failed at \${url}: \${response?.error?.message ?? "no answer"}\`);
      }
      const result = response.result as { protocolVersion?: string } | undefined;
      const opened: Session = {
        id: headers.get("mcp-session-id"),
        protocolVersion: result?.protocolVersion ?? PROTOCOL_VERSION,
      };
      await post(url, env, opened, { jsonrpc: "2.0", method: "notifications/initialized" });
      return opened;
    })();
    sessions.set(url, session);
    session.catch(() => sessions.delete(url));
  }
  return session;
}

/**
 * Calls one tool. Returns its structured content when it has one, otherwise its
 * content blocks; a tool error is thrown.
 */
export async function callTool(server: string, tool: string, args: unknown): Promise<unknown> {
  const env = runEnv();
  const url = endpoint(server, env);
  const session = await openSession(url, env);
  const { response } = await post(url, env, session, {
    jsonrpc: "2.0",
    id: nextId++,
    method: "tools/call",
    params: { name: tool, arguments: args ?? {} },
  });
  if (!response) throw new Error(\`\${server}.\${tool}: no answer\`);
  if (response.error) throw new Error(\`\${server}.\${tool}: \${response.error.message ?? "failed"}\`);
  const result = (response.result ?? {}) as ToolCallResult;
  if (result.isError) {
    const text = (result.content ?? []).map((block) => block.text ?? "").join("\\n");
    throw new Error(\`\${server}.\${tool}: \${text || "failed"}\`);
  }
  return result.structuredContent ?? result.content ?? [];
}
`;

function asSchema(value: unknown): JsonSchema | null {
  return value && typeof value === "object" && !Array.isArray(value) ? (value as JsonSchema) : null;
}

/** Code-unit order, so the layout never depends on the host's locale. */
function byCodeUnit(a: string, b: string): number {
  if (a === b) return 0;
  return a < b ? -1 : 1;
}

function sanitizeName(name: string): string {
  const cleaned = name.replace(/[^A-Za-z0-9_]/g, "_");
  return /^[0-9]/.test(cleaned) ? `_${cleaned}` : cleaned || "_";
}

function camelCase(stem: string): string {
  const parts = stem.split("_").filter(Boolean);
  const joined = parts
    .map((part, index) => (index === 0 ? part : part[0]!.toUpperCase() + part.slice(1)))
    .join("");
  const identifier = joined && IDENTIFIER.test(joined) ? joined : `_${joined}`;
  return RESERVED_WORDS.has(identifier) ? `${identifier}Tool` : identifier;
}

function pascalCase(stem: string): string {
  const joined = stem
    .split("_")
    .filter(Boolean)
    .map((part) => part[0]!.toUpperCase() + part.slice(1))
    .join("");
  return IDENTIFIER.test(joined) ? joined : `T${joined}`;
}

function propertyKey(key: string): string {
  return IDENTIFIER.test(key) ? key : JSON.stringify(key);
}

function docComment(text: string | undefined, indent: string): string {
  const lines = (text ?? "")
    .replaceAll("*/", "*\\/")
    .split(/\r?\n/)
    .map((line) => line.trimEnd());
  while (lines.length > 0 && !lines[lines.length - 1]) lines.pop();
  if (lines.length === 0 || (lines.length === 1 && !lines[0])) return "";
  if (lines.length === 1) return `${indent}/** ${lines[0]} */\n`;
  return `${indent}/**\n${lines.map((line) => `${indent} *${line ? ` ${line}` : ""}`).join("\n")}\n${indent} */\n`;
}

/** The schema a type is rendered from and the document its local `$ref`s point into. */
interface SchemaScope {
  root: JsonSchema;
  indent: string;
  depth: number;
}

function deeper(scope: SchemaScope, indent = scope.indent): SchemaScope {
  return { root: scope.root, indent, depth: scope.depth + 1 };
}

/** A `#/...` JSON pointer into the root schema; anything else is not resolved. */
function resolveRef(ref: unknown, root: JsonSchema): JsonSchema | null {
  if (ref === "#") return root;
  if (typeof ref !== "string" || !ref.startsWith("#/")) return null;
  let target: unknown = root;
  for (const raw of ref.slice(2).split("/")) {
    let segment: string;
    try {
      segment = decodeURIComponent(raw).replaceAll("~1", "/").replaceAll("~0", "~");
    } catch {
      return null;
    }
    const container = asSchema(target) ?? (Array.isArray(target) ? target : null);
    if (!container || !Object.hasOwn(container, segment)) return null;
    target = (container as Record<string, unknown>)[segment];
  }
  return asSchema(target);
}

function unionOf(members: string[]): string {
  const unique = [...new Set(members)];
  if (unique.includes("unknown")) return "unknown";
  return unique.join(" | ") || "never";
}

function intersectionOf(members: string[]): string {
  // `unknown` is the identity of an intersection.
  const known = [...new Set(members)].filter((member) => member !== "unknown");
  if (known.length === 0) return "unknown";
  if (known.length === 1) return known[0]!;
  return known.map((member) => `(${member})`).join(" & ");
}

function arrayOf(type: string): string {
  return /^[A-Za-z_$][\w$]*$/.test(type) ? `${type}[]` : `Array<${type}>`;
}

function objectBody(schema: JsonSchema, scope: SchemaScope): string {
  const properties = asSchema(schema.properties) ?? {};
  const required = new Set(Array.isArray(schema.required) ? (schema.required as string[]) : []);
  const inner = `${scope.indent}  `;
  const lines = Object.entries(properties).map(([key, value]) => {
    const property = asSchema(value) ?? {};
    const description = typeof property.description === "string" ? property.description : undefined;
    const optional = required.has(key) ? "" : "?";
    return `${docComment(description, inner)}${inner}${propertyKey(key)}${optional}: ${typeOf(property, deeper(scope, inner))};`;
  });
  return lines.length === 0 ? "{}" : `{\n${lines.join("\n")}\n${scope.indent}}`;
}

/** The type of a schema built from other schemas (const, enum, anyOf, oneOf, allOf, a type list). */
function composedTypeOf(schema: JsonSchema, scope: SchemaScope): string | null {
  if (schema.const !== undefined) return JSON.stringify(schema.const);
  if (Array.isArray(schema.enum)) return unionOf(schema.enum.map((value) => JSON.stringify(value)));
  const alternatives = Array.isArray(schema.anyOf) ? schema.anyOf : schema.oneOf;
  if (Array.isArray(alternatives)) {
    return unionOf(alternatives.map((member) => typeOf(asSchema(member), deeper(scope))));
  }
  if (Array.isArray(schema.allOf)) {
    return intersectionOf(schema.allOf.map((member) => typeOf(asSchema(member), deeper(scope))));
  }
  if (Array.isArray(schema.type)) {
    return unionOf(schema.type.map((type) => typeOf({ ...schema, type }, deeper(scope))));
  }
  return null;
}

/** The TypeScript type of a schema; `unknown` where no precise type can be given. */
function typeOf(schema: JsonSchema | null, scope: SchemaScope): string {
  if (!schema || scope.depth > MAX_SCHEMA_DEPTH) return "unknown";
  if (schema.$ref !== undefined) return typeOf(resolveRef(schema.$ref, scope.root), deeper(scope));
  const composed = composedTypeOf(schema, scope);
  if (composed !== null) return composed;
  switch (schema.type) {
    case "string":
      return "string";
    case "number":
    case "integer":
      return "number";
    case "boolean":
      return "boolean";
    case "null":
      return "null";
    case "array":
      return arrayOf(typeOf(asSchema(schema.items), deeper(scope)));
    case "object":
    case undefined: {
      if (asSchema(schema.properties)) return objectBody(schema, scope);
      const additional = asSchema(schema.additionalProperties);
      if (additional) return `Record<string, ${typeOf(additional, deeper(scope))}>`;
      return schema.type === "object" ? "Record<string, unknown>" : "unknown";
    }
    default:
      return "unknown";
  }
}

/** An object schema with listed properties and nothing composed: it renders as an interface. */
function isPlainObjectSchema(schema: JsonSchema): boolean {
  return (
    schema.$ref === undefined &&
    schema.const === undefined &&
    !Array.isArray(schema.enum) &&
    !Array.isArray(schema.anyOf) &&
    !Array.isArray(schema.oneOf) &&
    !Array.isArray(schema.allOf) &&
    (schema.type === "object" || schema.type === undefined) &&
    asSchema(schema.properties) !== null
  );
}

function declareType(name: string, schema: JsonSchema): string {
  const type = typeOf(schema, { root: schema, indent: "", depth: 0 });
  return isPlainObjectSchema(schema)
    ? `export interface ${name} ${type}\n`
    : `export type ${name} = ${type};\n`;
}

/** Whether a call may leave the input out: the input type takes `{}`. */
function acceptsEmptyInput(schema: JsonSchema): boolean {
  if (isPlainObjectSchema(schema)) {
    return !Array.isArray(schema.required) || schema.required.length === 0;
  }
  const type = typeOf(schema, { root: schema, indent: "", depth: 0 });
  return type === "unknown" || type.startsWith("Record<string, ");
}

/**
 * The client module's name inside a tool file. Generated names hold only
 * letters, digits and `_`, so no tool can collide with it.
 */
const CLIENT = "$client";

interface ToolLayout {
  tool: ToolTreeTool;
  /** File name in the server's directory. */
  file: string;
  functionName: string;
  /** Prefix of the tool's `Input` and `Output` types. */
  typeName: string;
}

interface ServerLayout {
  server: ToolTreeServer;
  /** Directory name under `servers/`. */
  dir: string;
  tools: ToolLayout[];
}

/** The first of `base`, `base_2`, `base_3`, ... that `isFree` accepts. */
function allocate(base: string, isFree: (candidate: string) => boolean): string {
  for (let suffix = 1; ; suffix += 1) {
    const candidate = suffix === 1 ? base : `${base}_${suffix}`;
    if (isFree(candidate)) return candidate;
  }
}

function layoutTools(tools: ToolTreeTool[]): ToolLayout[] {
  // File names are compared without case so the tree survives a case-insensitive disk.
  const usedFiles = new Set(["index"]);
  // Every name a server's barrel re-exports.
  const usedExports = new Set<string>();
  // Tools whose names are already clean claim them first; the rest take what is left.
  const isClean = (tool: ToolTreeTool) => sanitizeName(tool.name) === tool.name;
  const byName = (a: ToolTreeTool, b: ToolTreeTool) => byCodeUnit(a.name, b.name);
  return [...tools.filter(isClean).sort(byName), ...tools.filter((t) => !isClean(t)).sort(byName)]
    .map((tool) => {
      const stem = allocate(sanitizeName(tool.name), (candidate) => {
        const typeName = pascalCase(candidate);
        return (
          !usedFiles.has(candidate.toLowerCase()) &&
          ![camelCase(candidate), `${typeName}Input`, `${typeName}Output`].some((name) =>
            usedExports.has(name),
          )
        );
      });
      const layout: ToolLayout = {
        tool,
        file: `${stem}.ts`,
        functionName: camelCase(stem),
        typeName: pascalCase(stem),
      };
      usedFiles.add(stem.toLowerCase());
      usedExports.add(layout.functionName);
      usedExports.add(`${layout.typeName}Input`);
      usedExports.add(`${layout.typeName}Output`);
      return layout;
    })
    .sort((a, b) => byName(a.tool, b.tool));
}

/**
 * Where every server and tool goes and what each is called: deterministic for
 * a tool list, one directory per server and one file per tool, with no two
 * names alike (`paseo` keeps its own name).
 */
function layoutToolTree(servers: ToolTreeServer[]): ServerLayout[] {
  const usedDirs = new Set<string>();
  return [...servers]
    .sort((a, b) => {
      if (a.name === PASEO_TOOL_TREE_SERVER || b.name === PASEO_TOOL_TREE_SERVER) {
        return a.name === PASEO_TOOL_TREE_SERVER ? -1 : 1;
      }
      return byCodeUnit(a.name, b.name);
    })
    .map((server) => {
      const base = /^[A-Za-z0-9_-]+$/.test(server.name) ? server.name : sanitizeName(server.name);
      const dir = allocate(base, (candidate) => !usedDirs.has(candidate.toLowerCase()));
      usedDirs.add(dir.toLowerCase());
      return { server, dir, tools: layoutTools(server.tools) };
    });
}

function renderToolFile(server: string, layout: ToolLayout): string {
  const { tool, functionName, typeName } = layout;
  const inputSchema = asSchema(tool.inputSchema) ?? { type: "object", properties: {} };
  const outputSchema = asSchema(tool.outputSchema);
  const inputType = `${typeName}Input`;
  const outputType = outputSchema ? `${typeName}Output` : `${CLIENT}.ToolContent`;
  const parts = [
    `// Generated by Paseo from the tool list of ${JSON.stringify(server)}. Regenerated when it changes; do not edit.\n`,
    `import * as ${CLIENT} from "../../client.ts";\n`,
    "\n",
    declareType(inputType, inputSchema),
  ];
  if (outputSchema) {
    parts.push("\n", declareType(outputType, outputSchema));
  }
  const parameter = acceptsEmptyInput(inputSchema)
    ? `input: ${inputType} = {}`
    : `input: ${inputType}`;
  parts.push(
    "\n",
    docComment(tool.description || tool.name, ""),
    `export function ${functionName}(${parameter}): Promise<${outputType}> {\n`,
    `  return ${CLIENT}.callTool(${JSON.stringify(server)}, ${JSON.stringify(tool.name)}, input) as Promise<${outputType}>;\n`,
    "}\n",
  );
  return parts.join("");
}

function renderReadme(layouts: ServerLayout[]): string {
  const lines = [
    "# Your tools",
    "",
    "Every tool you can use, one TypeScript file each, grouped by server. Read only the files you",
    "need. Call them from a script you run with Paseo's `exec` tool, which gives the run your",
    "credentials:",
    "",
    "```ts",
    'import { readFile } from "<this directory>/servers/paseo/read_file.ts";',
    'const file = await readFile({ path: "package.json" });',
    "```",
    "",
    "Run it with `node --experimental-strip-types script.ts` (or `bun script.ts`).",
    "",
  ];
  for (const layout of layouts) {
    lines.push(`## ${layout.server.name}`, "");
    for (const tool of layout.tools) {
      lines.push(
        `- \`servers/${layout.dir}/${tool.file}\` — \`${tool.functionName}\` calls ${JSON.stringify(tool.tool.name)}`,
      );
    }
    lines.push("");
  }
  return lines.join("\n");
}

/** The tree's files by relative path. */
export function renderToolTree(servers: ToolTreeServer[]): Map<string, string> {
  const files = new Map<string, string>();
  files.set("client.ts", CLIENT_SOURCE);
  files.set("package.json", '{ "type": "module" }\n');
  const layouts = layoutToolTree(servers);
  for (const layout of layouts) {
    const dir = `servers/${layout.dir}`;
    for (const tool of layout.tools) {
      files.set(`${dir}/${tool.file}`, renderToolFile(layout.server.name, tool));
    }
    files.set(
      `${dir}/index.ts`,
      layout.tools
        .map((tool) => tool.file)
        .sort(byCodeUnit)
        .map((file) => `export * from "./${file}";\n`)
        .join(""),
    );
  }
  files.set("README.md", renderReadme(layouts));
  return files;
}

function digestOf(files: Map<string, string>): string {
  const hash = createHash("sha256");
  for (const [file, content] of [...files.entries()].sort(([a], [b]) => byCodeUnit(a, b))) {
    hash.update(file).update("\0").update(content).update("\0");
  }
  return hash.digest("hex");
}

/**
 * Writes the tree into `dir`, replacing what was there, unless the rendered
 * tree is the one already written.
 */
export async function writeToolTree(
  dir: string,
  servers: ToolTreeServer[],
): Promise<{ written: boolean }> {
  const files = renderToolTree(servers);
  const digest = digestOf(files);
  const current = await readFile(path.join(dir, DIGEST_FILE), "utf8").catch(() => null);
  if (current === digest) {
    return { written: false };
  }
  await mkdir(path.dirname(dir), { recursive: true });
  const suffix = randomBytes(6).toString("hex");
  const staging = `${dir}.tmp-${suffix}`;
  const retired = `${dir}.old-${suffix}`;
  try {
    for (const [file, content] of files) {
      const target = path.join(staging, file);
      await mkdir(path.dirname(target), { recursive: true });
      await writeFile(target, content);
    }
    await writeFile(path.join(staging, DIGEST_FILE), digest);
    const hadTree = await rename(dir, retired).then(
      () => true,
      (error: NodeJS.ErrnoException) => {
        if (error.code === "ENOENT") return false;
        throw error;
      },
    );
    await rename(staging, dir);
    if (hadTree) await rm(retired, { recursive: true, force: true });
  } finally {
    await rm(staging, { recursive: true, force: true });
  }
  return { written: true };
}
