import { createHash, randomBytes } from "node:crypto";
import { mkdir, readFile, rename, rm, writeFile } from "node:fs/promises";
import path from "node:path";

/**
 * The tool tree: the tools an agent sees, rendered as TypeScript it can list,
 * read and import from code (https://www.anthropic.com/engineering/code-execution-with-mcp).
 * One directory per server, one file per tool, each a typed function that
 * calls the tool through Paseo with the run's own credentials.
 */

export type JsonSchema = Record<string, unknown>;

export interface ToolTreeTool {
  name: string;
  description?: string;
  inputSchema?: JsonSchema;
  outputSchema?: JsonSchema;
}

export interface ToolTreeServer {
  /** `paseo` for the daemon's own tools; otherwise an MCP gateway backend name. */
  name: string;
  tools: ToolTreeTool[];
}

export const PASEO_TOOL_TREE_SERVER = "paseo";

const DIGEST_FILE = ".paseo-tool-tree-digest";
const MAX_SCHEMA_DEPTH = 8;
const IDENTIFIER = /^[A-Za-z_$][A-Za-z0-9_$]*$/;
const RESERVED_WORDS = new Set(
  (
    "break case catch class const continue debugger default delete do else enum export extends " +
    "false finally for function if import in instanceof new null return super switch this throw " +
    "true try typeof var void while with yield let static implements interface package private " +
    "protected public await arguments eval"
  ).split(" "),
);

const CLIENT_SOURCE = `// Generated by Paseo. Calls a tool through Paseo as the agent whose run this is:
// exec and process_spawn give each run PASEO_AGENT_TOKEN, PASEO_MCP_URL and
// PASEO_MCP_GATEWAY_URL. Nothing here holds a credential.

export type ToolContent = Array<{ type: string; text?: string; [key: string]: unknown }>;

interface RunEnv {
  token: string;
  mcpUrl: string;
  gatewayUrl: string | undefined;
}

interface ToolCallResult {
  content?: ToolContent;
  structuredContent?: unknown;
  isError?: boolean;
}

interface JsonRpcResponse {
  id?: number | string | null;
  result?: unknown;
  error?: { code?: number; message?: string };
}

interface Session {
  id: string | null;
  protocolVersion: string;
}

const PROTOCOL_VERSION = "2025-06-18";
const sessions = new Map<string, Promise<Session>>();
let nextId = 1;

function runEnv(): RunEnv {
  const env =
    (globalThis as { process?: { env?: Record<string, string | undefined> } }).process?.env ?? {};
  const token = env.PASEO_AGENT_TOKEN;
  const mcpUrl = env.PASEO_MCP_URL;
  if (!token || !mcpUrl) {
    throw new Error(
      "PASEO_AGENT_TOKEN and PASEO_MCP_URL are not set: run this code with Paseo's exec tool.",
    );
  }
  return { token, mcpUrl, gatewayUrl: env.PASEO_MCP_GATEWAY_URL };
}

function endpoint(server: string, env: RunEnv): string {
  if (server === "paseo") return env.mcpUrl;
  if (!env.gatewayUrl) throw new Error("PASEO_MCP_GATEWAY_URL is not set");
  return \`\${env.gatewayUrl.replace(/\\/+$/, "")}/\${encodeURIComponent(server)}\`;
}

function parseBody(text: string, contentType: string): JsonRpcResponse[] {
  if (!text.trim()) return [];
  if (!contentType.includes("text/event-stream")) {
    const parsed = JSON.parse(text) as JsonRpcResponse | JsonRpcResponse[];
    return Array.isArray(parsed) ? parsed : [parsed];
  }
  const messages: JsonRpcResponse[] = [];
  for (const event of text.split(/\\r?\\n\\r?\\n/)) {
    const data = event
      .split(/\\r?\\n/)
      .filter((line) => line.startsWith("data:"))
      .map((line) => line.slice(5).trimStart())
      .join("\\n");
    if (data) messages.push(JSON.parse(data) as JsonRpcResponse);
  }
  return messages;
}

async function post(
  url: string,
  env: RunEnv,
  session: Session | null,
  message: Record<string, unknown>,
): Promise<{ headers: Headers; response: JsonRpcResponse | null }> {
  const headers: Record<string, string> = {
    "content-type": "application/json",
    accept: "application/json, text/event-stream",
    authorization: \`Bearer \${env.token}\`,
  };
  if (session?.id) headers["mcp-session-id"] = session.id;
  if (session) headers["mcp-protocol-version"] = session.protocolVersion;
  const res = await fetch(url, { method: "POST", headers, body: JSON.stringify(message) });
  const text = await res.text();
  if (!res.ok) {
    throw new Error(\`\${url} answered \${res.status}: \${text.slice(0, 500)}\`);
  }
  const id = message.id;
  const response =
    id === undefined
      ? null
      : (parseBody(text, res.headers.get("content-type") ?? "").find((m) => m.id === id) ?? null);
  return { headers: res.headers, response };
}

function openSession(url: string, env: RunEnv): Promise<Session> {
  let session = sessions.get(url);
  if (!session) {
    session = (async () => {
      const { headers, response } = await post(url, env, null, {
        jsonrpc: "2.0",
        id: nextId++,
        method: "initialize",
        params: {
          protocolVersion: PROTOCOL_VERSION,
          capabilities: {},
          clientInfo: { name: "paseo-tool-tree", version: "1" },
        },
      });
      if (!response || response.error) {
        throw new Error(\`MCP initialize failed at \${url}: \${response?.error?.message ?? "no answer"}\`);
      }
      const result = response.result as { protocolVersion?: string } | undefined;
      const opened: Session = {
        id: headers.get("mcp-session-id"),
        protocolVersion: result?.protocolVersion ?? PROTOCOL_VERSION,
      };
      await post(url, env, opened, { jsonrpc: "2.0", method: "notifications/initialized" });
      return opened;
    })();
    sessions.set(url, session);
    session.catch(() => sessions.delete(url));
  }
  return session;
}

/**
 * Calls one tool. Returns its structured content when it has one, otherwise its
 * content blocks; a tool error is thrown.
 */
export async function callTool(server: string, tool: string, args: unknown): Promise<unknown> {
  const env = runEnv();
  const url = endpoint(server, env);
  const session = await openSession(url, env);
  const { response } = await post(url, env, session, {
    jsonrpc: "2.0",
    id: nextId++,
    method: "tools/call",
    params: { name: tool, arguments: args ?? {} },
  });
  if (!response) throw new Error(\`\${server}.\${tool}: no answer\`);
  if (response.error) throw new Error(\`\${server}.\${tool}: \${response.error.message ?? "failed"}\`);
  const result = (response.result ?? {}) as ToolCallResult;
  if (result.isError) {
    const text = (result.content ?? []).map((block) => block.text ?? "").join("\\n");
    throw new Error(\`\${server}.\${tool}: \${text || "failed"}\`);
  }
  return result.structuredContent ?? result.content ?? [];
}
`;

function asSchema(value: unknown): JsonSchema | null {
  return value && typeof value === "object" && !Array.isArray(value) ? (value as JsonSchema) : null;
}

function sanitizeName(name: string): string {
  const cleaned = name.replace(/[^A-Za-z0-9_]/g, "_");
  return /^[0-9]/.test(cleaned) ? `_${cleaned}` : cleaned || "_";
}

function camelCase(name: string): string {
  const parts = sanitizeName(name).split("_").filter(Boolean);
  const joined = parts
    .map((part, index) => (index === 0 ? part : part[0]!.toUpperCase() + part.slice(1)))
    .join("");
  const identifier = joined && IDENTIFIER.test(joined) ? joined : `_${joined}`;
  return RESERVED_WORDS.has(identifier) ? `${identifier}Tool` : identifier;
}

function pascalCase(name: string): string {
  const joined = sanitizeName(name)
    .split("_")
    .filter(Boolean)
    .map((part) => part[0]!.toUpperCase() + part.slice(1))
    .join("");
  return IDENTIFIER.test(joined) ? joined : `T${joined}`;
}

function propertyKey(key: string): string {
  return IDENTIFIER.test(key) ? key : JSON.stringify(key);
}

function docComment(text: string | undefined, indent: string): string {
  const lines = (text ?? "")
    .replaceAll("*/", "*\\/")
    .split(/\r?\n/)
    .map((line) => line.trimEnd());
  while (lines.length > 0 && !lines[lines.length - 1]) lines.pop();
  if (lines.length === 0 || (lines.length === 1 && !lines[0])) return "";
  if (lines.length === 1) return `${indent}/** ${lines[0]} */\n`;
  return `${indent}/**\n${lines.map((line) => `${indent} *${line ? ` ${line}` : ""}`).join("\n")}\n${indent} */\n`;
}

function unionOf(members: string[]): string {
  const unique = [...new Set(members)];
  if (unique.includes("unknown")) return "unknown";
  return unique.join(" | ") || "never";
}

function wrapForArray(type: string): string {
  return /[|&]/.test(type) && !type.startsWith("{") ? `(${type})` : type;
}

function objectBody(schema: JsonSchema, indent: string, depth: number): string {
  const properties = asSchema(schema.properties) ?? {};
  const required = new Set(Array.isArray(schema.required) ? (schema.required as string[]) : []);
  const inner = `${indent}  `;
  const lines = Object.entries(properties).map(([key, value]) => {
    const property = asSchema(value) ?? {};
    const description = typeof property.description === "string" ? property.description : undefined;
    const optional = required.has(key) ? "" : "?";
    return `${docComment(description, inner)}${inner}${propertyKey(key)}${optional}: ${typeOf(property, inner, depth + 1)};`;
  });
  return lines.length === 0 ? "{}" : `{\n${lines.join("\n")}\n${indent}}`;
}

/** The type of a schema built from other schemas (const, enum, anyOf, oneOf, allOf, a type list). */
function composedTypeOf(schema: JsonSchema, indent: string, depth: number): string | null {
  if (schema.const !== undefined) return JSON.stringify(schema.const);
  if (Array.isArray(schema.enum)) return unionOf(schema.enum.map((value) => JSON.stringify(value)));
  const alternatives = Array.isArray(schema.anyOf) ? schema.anyOf : schema.oneOf;
  if (Array.isArray(alternatives)) {
    return unionOf(alternatives.map((member) => typeOf(asSchema(member), indent, depth + 1)));
  }
  if (Array.isArray(schema.allOf)) {
    const members = schema.allOf.map((member) => typeOf(asSchema(member), indent, depth + 1));
    return members.includes("unknown") ? "unknown" : members.join(" & ");
  }
  if (Array.isArray(schema.type)) {
    return unionOf(schema.type.map((type) => typeOf({ ...schema, type }, indent, depth + 1)));
  }
  return null;
}

function typeOf(schema: JsonSchema | null, indent: string, depth: number): string {
  if (!schema || depth > MAX_SCHEMA_DEPTH || schema.$ref !== undefined) return "unknown";
  const composed = composedTypeOf(schema, indent, depth);
  if (composed !== null) return composed;
  switch (schema.type) {
    case "string":
      return "string";
    case "number":
    case "integer":
      return "number";
    case "boolean":
      return "boolean";
    case "null":
      return "null";
    case "array": {
      const items = asSchema(schema.items);
      return `${wrapForArray(typeOf(items, indent, depth + 1))}[]`;
    }
    case "object":
    case undefined: {
      if (asSchema(schema.properties)) return objectBody(schema, indent, depth);
      const additional = asSchema(schema.additionalProperties);
      if (additional) return `Record<string, ${typeOf(additional, indent, depth + 1)}>`;
      return schema.type === "object" ? "Record<string, unknown>" : "unknown";
    }
    default:
      return "unknown";
  }
}

function declareType(name: string, schema: JsonSchema | null): string {
  const type = typeOf(schema, "", 0);
  return type.startsWith("{")
    ? `export interface ${name} ${type}\n`
    : `export type ${name} = ${type};\n`;
}

function hasRequiredInput(schema: JsonSchema | null): boolean {
  return Array.isArray(schema?.required) && (schema.required as unknown[]).length > 0;
}

function renderToolFile(server: string, tool: ToolTreeTool): string {
  const functionName = camelCase(tool.name);
  const typeName = pascalCase(tool.name);
  const inputSchema = asSchema(tool.inputSchema) ?? { type: "object", properties: {} };
  const outputSchema = asSchema(tool.outputSchema);
  const inputType = `${typeName}Input`;
  const outputType = outputSchema ? `${typeName}Output` : "ToolContent";
  const parts = [
    `// Generated by Paseo from the tool list of "${server}". Regenerated when it changes; do not edit.\n`,
    outputSchema
      ? 'import { callTool } from "../../client.ts";\n'
      : 'import { callTool, type ToolContent } from "../../client.ts";\n',
    "\n",
    declareType(inputType, inputSchema),
  ];
  if (outputSchema) {
    parts.push("\n", declareType(outputType, outputSchema));
  }
  const parameter = hasRequiredInput(inputSchema)
    ? `input: ${inputType}`
    : `input: ${inputType} = {}`;
  parts.push(
    "\n",
    docComment(tool.description || tool.name, ""),
    `export function ${functionName}(${parameter}): Promise<${outputType}> {\n`,
    `  return callTool(${JSON.stringify(server)}, ${JSON.stringify(tool.name)}, input) as Promise<${outputType}>;\n`,
    "}\n",
  );
  return parts.join("");
}

function serverDirName(name: string): string {
  return /^[A-Za-z0-9_-]+$/.test(name) ? name : sanitizeName(name);
}

function renderReadme(
  entries: Array<{ server: string; files: Array<{ file: string; tool: string }> }>,
): string {
  const lines = [
    "# Your tools",
    "",
    "Every tool you can use, one TypeScript file each, grouped by server. Read only the files you",
    "need. Call them from a script you run with Paseo's `exec` tool, which gives the run your",
    "credentials:",
    "",
    "```ts",
    'import { readFile } from "<this directory>/servers/paseo/read_file.ts";',
    'const file = await readFile({ path: "package.json" });',
    "```",
    "",
    "Run it with `node --experimental-strip-types script.ts` (or `bun script.ts`).",
    "",
  ];
  for (const entry of entries) {
    lines.push(`## ${entry.server}`, "");
    for (const file of entry.files) {
      lines.push(`- \`servers/${serverDirName(entry.server)}/${file.file}\` — ${file.tool}`);
    }
    lines.push("");
  }
  return lines.join("\n");
}

/** The tree's files by relative path. */
export function renderToolTree(servers: ToolTreeServer[]): Map<string, string> {
  const files = new Map<string, string>();
  files.set("client.ts", CLIENT_SOURCE);
  files.set("package.json", '{ "type": "module" }\n');
  const readme: Array<{ server: string; files: Array<{ file: string; tool: string }> }> = [];
  for (const server of [...servers].sort((a, b) => a.name.localeCompare(b.name))) {
    const dir = `servers/${serverDirName(server.name)}`;
    const used = new Set<string>();
    const listed: Array<{ file: string; tool: string }> = [];
    for (const tool of [...server.tools].sort((a, b) => a.name.localeCompare(b.name))) {
      const base = sanitizeName(tool.name);
      let file = `${base}.ts`;
      for (let suffix = 2; used.has(file); suffix += 1) file = `${base}_${suffix}.ts`;
      used.add(file);
      files.set(`${dir}/${file}`, renderToolFile(server.name, tool));
      listed.push({ file, tool: tool.name });
    }
    files.set(
      `${dir}/index.ts`,
      listed
        .map((entry) => entry.file)
        .sort()
        .map((file) => `export * from "./${file}";\n`)
        .join(""),
    );
    readme.push({ server: server.name, files: listed });
  }
  files.set("README.md", renderReadme(readme));
  return files;
}

function digestOf(files: Map<string, string>): string {
  const hash = createHash("sha256");
  for (const [file, content] of [...files.entries()].sort(([a], [b]) => a.localeCompare(b))) {
    hash.update(file).update("\0").update(content).update("\0");
  }
  return hash.digest("hex");
}

/**
 * Writes the tree into `dir`, replacing what was there, unless the rendered
 * tree is the one already written.
 */
export async function writeToolTree(
  dir: string,
  servers: ToolTreeServer[],
): Promise<{ written: boolean }> {
  const files = renderToolTree(servers);
  const digest = digestOf(files);
  const current = await readFile(path.join(dir, DIGEST_FILE), "utf8").catch(() => null);
  if (current === digest) {
    return { written: false };
  }
  await mkdir(path.dirname(dir), { recursive: true });
  const suffix = randomBytes(6).toString("hex");
  const staging = `${dir}.tmp-${suffix}`;
  const retired = `${dir}.old-${suffix}`;
  try {
    for (const [file, content] of files) {
      const target = path.join(staging, file);
      await mkdir(path.dirname(target), { recursive: true });
      await writeFile(target, content);
    }
    await writeFile(path.join(staging, DIGEST_FILE), digest);
    const hadTree = await rename(dir, retired).then(
      () => true,
      (error: NodeJS.ErrnoException) => {
        if (error.code === "ENOENT") return false;
        throw error;
      },
    );
    await rename(staging, dir);
    if (hadTree) await rm(retired, { recursive: true, force: true });
  } finally {
    await rm(staging, { recursive: true, force: true });
  }
  return { written: true };
}
